version: "3.8"

services:
  aflat-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/project
    command: ["/aflat/bin/aflat", "run"]
